/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.38
 * Generated at: 2020-10-13 08:16:52 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class main_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(7);
    _jspx_dependants.put("/WEB-INF/views/aside.jsp", Long.valueOf(1602576888297L));
    _jspx_dependants.put("/WEB-INF/views/header.jsp", Long.valueOf(1602570450896L));
    _jspx_dependants.put("/WEB-INF/views/footer.jsp", Long.valueOf(1602570450896L));
    _jspx_dependants.put("jar:file:/C:/SpringProject/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/s20200903/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/views/includeJSP.jsp", Long.valueOf(1602576508926L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1457360714000L));
    _jspx_dependants.put("jar:file:/C:/SpringProject/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/s20200903/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fchoose;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fchoose = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fchoose.release();
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("        <meta charset=\"UTF-8\" />\r\n");
      out.write("        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />\r\n");
      out.write("        <title>회원가입 :: 당근나라</title>\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"css/common.css\" />\r\n");
      out.write("        <script\r\n");
      out.write("            src=\"https://kit.fontawesome.com/797af710b1.js\"\r\n");
      out.write("            crossorigin=\"anonymous\"\r\n");
      out.write("            defer\r\n");
      out.write("        ></script>\r\n");
      out.write("        <script\r\n");
      out.write("            src=\"https://t1.daumcdn.net/mapjsapi/bundle/postcode/prod/postcode.v2.js\"\r\n");
      out.write("            defer\r\n");
      out.write("        ></script>\r\n");
      out.write("        <link\r\n");
      out.write("            rel=\"shortcut icon\"\r\n");
      out.write("            type=\"image/x-icon\"\r\n");
      out.write("            href=\"https://d1unjqcospf8gs.cloudfront.net/favicon.ico\"\r\n");
      out.write("        />\r\n");
      out.write("        <link\r\n");
      out.write("            href=\"https://fonts.googleapis.com/css2?family=Noto+Sans+KR:wght@400;500;700;900&display=swap\"\r\n");
      out.write("            rel=\"stylesheet\"\r\n");
      out.write("        />\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("        <aside class=\"fixed__list\">\r\n");
      out.write("            <ul>\r\n");
      out.write("                <li><a href=\"JYnoticeBoard.do\">공지사항</a></li>\r\n");
      out.write("                <li><a href=\"../board/blackListBoard.html\">검거완료 !</a></li>\r\n");
      out.write("                <li>\r\n");
      out.write("                    <a href=\"../board/badReviewBoard.html\">불량거래 후기</a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li><a href=\"#\">판매중 이에요.</a></li>\r\n");
      out.write("                <li><a href=\"#\">나눔중 이에요.</a></li>\r\n");
      out.write("                <li><a href=\"buylist.do\">구매합니다 ~!</a></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("        </aside>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\t<meta charset=\"UTF-8\" />\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />\r\n");
      out.write("    <title>당근나라</title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/common.css\" />\r\n");
      out.write("        <script src=\"javascript/common.js\" defer></script>\r\n");
      out.write("        <script\r\n");
      out.write("            src=\"https://kit.fontawesome.com/797af710b1.js\"\r\n");
      out.write("            crossorigin=\"anonymous\"\r\n");
      out.write("            defer\r\n");
      out.write("        ></script>\r\n");
      out.write("        <script\r\n");
      out.write("            src=\"https://t1.daumcdn.net/mapjsapi/bundle/postcode/prod/postcode.v2.js\"\r\n");
      out.write("            defer\r\n");
      out.write("        ></script>\r\n");
      out.write("        <link\r\n");
      out.write("            rel=\"shortcut icon\"\r\n");
      out.write("            type=\"image/x-icon\"\r\n");
      out.write("            href=\"https://d1unjqcospf8gs.cloudfront.net/favicon.ico\"\r\n");
      out.write("        />\r\n");
      out.write("        <link\r\n");
      out.write("            href=\"https://fonts.googleapis.com/css2?family=Noto+Sans+KR:wght@400;500;700;900&display=swap\"\r\n");
      out.write("            rel=\"stylesheet\"\r\n");
      out.write("        />\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("        <!-- 메뉴 고정바 -->\r\n");
      out.write("        <header class=\"header\">\r\n");
      out.write("            <div class=\"header__fixed-bar\">\r\n");
      out.write("                <section class=\"header__fixed-bar-logo section-logo\">\r\n");
      out.write("                    <a href=\"main.do\">\r\n");
      out.write("                        <img\r\n");
      out.write("                            src=\"https://img1.daumcdn.net/thumb/R1280x0/?scode=mtistory2&fname=https%3A%2F%2Fblog.kakaocdn.net%2Fdn%2FSQxEt%2FbtqJs5kkQnP%2FhvX1kh8aeqli9J93tF5qV1%2Ftfile.svg\"\r\n");
      out.write("                            alt=\"당근마켓\"\r\n");
      out.write("                        />\r\n");
      out.write("                    </a>\r\n");
      out.write("                </section>\r\n");
      out.write("                <section class=\"header__fixed-bar-search section-search\">\r\n");
      out.write("                    <div class=\"header__fixed-bar-search-container\">\r\n");
      out.write("                    <form action=\"loginMember.do\" method=\"post\">\r\n");
      out.write("                        <input\r\n");
      out.write("                            class=\"search-input\"\r\n");
      out.write("                            type=\"text\"\r\n");
      out.write("                            name=\"sword\"\r\n");
      out.write("                            placeholder=\"동네 이름, 물품명 등을 검색해보세요!\"\r\n");
      out.write("                        />\r\n");
      out.write("                        <input\r\n");
      out.write("                            type=\"image\"\r\n");
      out.write("                            class=\"search-icon\"\r\n");
      out.write("                            src=\"https://img.icons8.com/ios-glyphs/30/000000/search.png\"\r\n");
      out.write("                        />\r\n");
      out.write("                    </form>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </section>\r\n");
      out.write("                <section class=\"header__fixed-bar-nav section-nav\">\r\n");
      out.write("                    <nav class=\"header__fixed-bar-nav-container\">\r\n");
      out.write("                    ");
      if (_jspx_meth_c_005fchoose_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("                    </nav>\r\n");
      out.write("                </section>\r\n");
      out.write("            </div>\r\n");
      out.write("        </header>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- <link href=\"css/common.css\" rel=\"stylesheet\" type=\"text/css\"> -->");
      out.write("\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("    <head>\r\n");
      out.write("        <meta charset=\"UTF-8\" />\r\n");
      out.write("        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />\r\n");
      out.write("        <title>당신 근처의 당근나라</title>\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"css/common.css\" />\r\n");
      out.write("        <script src=\"javascript/common.js\" defer></script>\r\n");
      out.write("        <script\r\n");
      out.write("            src=\"https://kit.fontawesome.com/797af710b1.js\"\r\n");
      out.write("            crossorigin=\"anonymous\"\r\n");
      out.write("            defer\r\n");
      out.write("        ></script>\r\n");
      out.write("        <link\r\n");
      out.write("            rel=\"shortcut icon\"\r\n");
      out.write("            type=\"image/x-icon\"\r\n");
      out.write("            href=\"https://img1.daumcdn.net/thumb/R1280x0/?scode=mtistory2&fname=https%3A%2F%2Fblog.kakaocdn.net%2Fdn%2Fcz9VUi%2FbtqJt0b2VUe%2FiiBIEnDkufPInk4hKsunE1%2Fimg.png\"\r\n");
      out.write("        />\r\n");
      out.write("        <link\r\n");
      out.write("            href=\"https://fonts.googleapis.com/css2?family=Noto+Sans+KR:wght@400;500;700;900&display=swap\"\r\n");
      out.write("            rel=\"stylesheet\"\r\n");
      out.write("        />\r\n");
      out.write("    </head>\r\n");
      out.write("\r\n");
      out.write("    <body>\r\n");
      out.write("        <!-- 섹션 시작 -->\r\n");
      out.write("        <section class=\"main__section section-1\">\r\n");
      out.write("            <div class=\"main__section-container\">\r\n");
      out.write("                <div class=\"main__section-content section-1-text\">\r\n");
      out.write("                    <h1>당신 근처의<br />당근나라</h1>\r\n");
      out.write("                    <p>\r\n");
      out.write("                        중고 거래부터 동네 정보까지, 이웃과 함께 해요 <br />\r\n");
      out.write("                        가깝고 따뜻한 당신의 근처를 만들어요.\r\n");
      out.write("                    </p>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"main__section-content section-1-image\"></div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </section>\r\n");
      out.write("        <section class=\"main__section section-2\">\r\n");
      out.write("            <div class=\"main__section-container\">\r\n");
      out.write("                <div class=\"main__section-content section-2-image\"></div>\r\n");
      out.write("                <div class=\"main__section-content section-2-text\">\r\n");
      out.write("                    <h1>우리 동네<br />중고 직거래 마켓</h1>\r\n");
      out.write("                    <p>동네 주민들과 가깝고 따뜻한 거래를 지금 경험해보세요.</p>\r\n");
      out.write("                    <div\r\n");
      out.write("                        class=\"main__section-content section2-button-container\"\r\n");
      out.write("                    >\r\n");
      out.write("                        <input\r\n");
      out.write("                            class=\"section-2-btn\"\r\n");
      out.write("                            type=\"button\"\r\n");
      out.write("                            value=\"인기매물 보기\"\r\n");
      out.write("                            onclick='location.href=\"https://www.daangn.com/hot_articles\"'\r\n");
      out.write("                        />\r\n");
      out.write("                        <input\r\n");
      out.write("                            class=\"section-2-btn\"\r\n");
      out.write("                            type=\"button\"\r\n");
      out.write("                            value=\"믿을 수 있는 중고거래\"\r\n");
      out.write("                            onclick='location.href=\"https://www.daangn.com/trust\"'\r\n");
      out.write("                        />\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </section>\r\n");
      out.write("        <section class=\"main__section section-3\">\r\n");
      out.write("            <div class=\"main__section-container\">\r\n");
      out.write("                <div class=\"main__section-content section-3-text\">\r\n");
      out.write("                    <h1>이웃과 함께 하는<br />동네 생활</h1>\r\n");
      out.write("                    <p>우리 동네의 다양한 이야기를 이웃과 함께 나누어요.</p>\r\n");
      out.write("                    <ul class=\"section-3-text-list\">\r\n");
      out.write("                        <li class=\"section-3-text-list-content\">\r\n");
      out.write("                            <div\r\n");
      out.write("                                class=\"section-3-text-list-content-icon icon-question\"\r\n");
      out.write("                            ></div>\r\n");
      out.write("                            <div>\r\n");
      out.write("                                <strong>우리동네질문</strong>\r\n");
      out.write("                                <p>\r\n");
      out.write("                                    궁금한 게 있을 땐<br />이웃에게 물어보세요.\r\n");
      out.write("                                </p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li class=\"section-3-text-list-content\">\r\n");
      out.write("                            <div\r\n");
      out.write("                                class=\"section-3-text-list-content-icon icon-lost\"\r\n");
      out.write("                            ></div>\r\n");
      out.write("                            <div>\r\n");
      out.write("                                <strong>동네분실센터</strong>\r\n");
      out.write("                                <p>\r\n");
      out.write("                                    무언가를 잃어버렸을때,<br />함께 찾을 수\r\n");
      out.write("                                    있어요.\r\n");
      out.write("                                </p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li class=\"section-3-text-list-content\">\r\n");
      out.write("                            <div\r\n");
      out.write("                                class=\"section-3-text-list-content-icon icon-group\"\r\n");
      out.write("                            ></div>\r\n");
      out.write("                            <div>\r\n");
      out.write("                                <strong>동네모임</strong>\r\n");
      out.write("                                <p>\r\n");
      out.write("                                    관심사가 비슷한 이웃과<br />온오프라인으로\r\n");
      out.write("                                    만나요.\r\n");
      out.write("                                </p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"main__section-content section-3-image\"></div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </section>\r\n");
      out.write("        <section class=\"main__section section-4\">\r\n");
      out.write("            <div class=\"main__section-container\">\r\n");
      out.write("                <div class=\"main__section-content section-4-image\"></div>\r\n");
      out.write("                <div class=\"main__section-content section-4-text\">\r\n");
      out.write("                    <h1>내 근처에서 찾는<br />우리 나눔 장터</h1>\r\n");
      out.write("                    <p>\r\n");
      out.write("                        우리 동네 나눔을 찾고 있나요?<br />동네 주민과 함께\r\n");
      out.write("                        나눔을 해보아요.\r\n");
      out.write("                    </p>\r\n");
      out.write("                    <div\r\n");
      out.write("                        class=\"main__section-content section4-button-container\"\r\n");
      out.write("                    >\r\n");
      out.write("                        <input\r\n");
      out.write("                            class=\"section-4-btn\"\r\n");
      out.write("                            type=\"button\"\r\n");
      out.write("                            value=\"우리동네 나눔글 찾기\"\r\n");
      out.write("                            onclick='location.href=\"https://town.daangn.com/\"'\r\n");
      out.write("                        />\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </section>\r\n");
      out.write("        <!-- 실시간 채팅 아이콘 -->\r\n");
      out.write("        <div class=\"chat-container\">\r\n");
      out.write("            <div class=\"chat-container__relative\">\r\n");
      out.write("                <div class=\"chat-container__icon\">\r\n");
      out.write("                    <!-- 새로운 메세지 있을때만 -->\r\n");
      out.write("                    <div class=\"chat-container__icon--new\">N</div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"chat-container__items\">\r\n");
      out.write("                    <div class=\"chat-container__header\">chat</div>\r\n");
      out.write("                    <ul class=\"chat-container__list\">\r\n");
      out.write("                        <li class=\"chat-container__item\">\r\n");
      out.write("                            <a class=\"chat-container__link\" href=\"#none\">\r\n");
      out.write("                                <div class=\"chat-container__text\">\r\n");
      out.write("                                    <strong class=\"chat-container__nick\"\r\n");
      out.write("                                        >닉네임</strong\r\n");
      out.write("                                    >\r\n");
      out.write("                                    <p class=\"chat-container__summary\">\r\n");
      out.write("                                        채팅창 메세지채팅창 메세지채팅창\r\n");
      out.write("                                        메세지채팅창 메세지채팅창 메세지채팅창\r\n");
      out.write("                                        메세지채팅창 메세지채팅창 메세지채팅창\r\n");
      out.write("                                        메세지\r\n");
      out.write("                                    </p>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"chat-container__info\">\r\n");
      out.write("                                    <p class=\"chat-container__date\">\r\n");
      out.write("                                        2020.10.06\r\n");
      out.write("                                    </p>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </a>\r\n");
      out.write("                            <div class=\"chat-container__delete\">\r\n");
      out.write("                                나가기\r\n");
      out.write("                                <img\r\n");
      out.write("                                    src=\"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAGQAAABkCAYAAABw4pVUAAAABmJLR0QA/wD/AP+gvaeTAAACnElEQVR4nO3dv27TUABG8dMIJoYWMTPwEjwBCwNigJYKCnRB8HRI7IzsMMLUFTGlCDFAKQwu0D/XECfXvZ/q85O8VIl95RO7SnzjADwDvgI/J7bsA9uEWQO+AFdaD6SROXANOGw9kN/W6F4tU3aVLkyEWesB6KRLhb/doDu/XkTrwF7rQfxLKcicoEO4svjTs6esMAYJY5AwBgljkDAGCWOQMAYJY5AwBgljkDAGCWOQMAYJY5AwBglTukB1kc3p5hHE8ggJY5AwBgljkDAGCWOQMAYJY5DhrgOvgNfArTE2cHqa/sYYG7lAXvJ3X30HNmtvwCDDvOHk/qoexSDD3KaLcDrKVq0NGGS4e8A3Tu63A2CnxsoNspz7nD1SqkQxyPJGiWKQ1VSPYpDVbVKO8niZlRmkjmpRDFLPFuUoT4asxCB1rRzFIPU9oBzl6SJPNsg4SlF+sEAUg4xnm+7IGBTFIOPqi7Lb9wSDjG+XLsLx/XwIvCg92CDnY+EorYLsAJ8K25/acub01SLIZaZ507S+5YCjm6m1uqY+OxqIClocIQAPgY+F7U9tiThlTVHfP/Xnpx9okPGVYvS+FzHIuAa/WzfIePzoJMjSn/gapL6+GAtdEzFIXV6gCtIXY9B1dYPU4SSHIH0xlpqbZZDVOFEuiFNJgzjZOkjf1xEe1Vi5QYa5i1/YifKBszH8SltD7xgxBhhkqJvAW+A9cGeMDRgkiDcOCGOQMAYJY5AwBgljkDAGCTO1IBuEv++aWpB4BgljkDAGCWOQMAYJY5AwBgljkDAGCWOQMAYJY5AwBgljkDAGCVP6YckNwn98cQXrrQfwP6Uge+c+Cv3hKSvMDNhvPYiG5sDn1oM4bkZ3z78pRpnT3RrpsPVAjvsFW3N9LhOsh0kAAAAASUVORK5CYII=\"\r\n");
      out.write("                                />\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"chat-container__new\">N</div>\r\n");
      out.write("                        </li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("                <!-- 채팅방 -->\r\n");
      out.write("                <div class=\"chat-container__chat-room\">\r\n");
      out.write("                    <div class=\"chat-container__chat-room--header\">\r\n");
      out.write("                        <a class=\"chat-container__chat-room--back\" href=\"#none\"\r\n");
      out.write("                            ><i class=\"fas fa-arrow-left\"></i></a\r\n");
      out.write("                        >상대방 닉네임\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <ul class=\"chat-container__chat-room__list\">\r\n");
      out.write("                        <li class=\"chat-container__chat-room__received\">\r\n");
      out.write("                            <div class=\"message__img\">\r\n");
      out.write("                                <i class=\"fas fa-carrot\"></i>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"message__container\">\r\n");
      out.write("                                <div class=\"message__author\">\r\n");
      out.write("                                    <a href=\"../member/userDetail.html\"\r\n");
      out.write("                                        >상대방아이디</a\r\n");
      out.write("                                    ><span class=\"message__container--date\"\r\n");
      out.write("                                        >2020.10.06 16:04</span\r\n");
      out.write("                                    >\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"message__content-received\">\r\n");
      out.write("                                    Congrats XD <br />\r\n");
      out.write("                                    Congrats XD <br />\r\n");
      out.write("                                    Congrats XD <br />\r\n");
      out.write("                                    Congrats XD <br />\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li class=\"chat-container__chat-room__sent\">\r\n");
      out.write("                            <div class=\"message__container-sent\">\r\n");
      out.write("                                <div class=\"message__author\">\r\n");
      out.write("                                    <span class=\"message__container--date\"\r\n");
      out.write("                                        >2020.10.06 16:08</span\r\n");
      out.write("                                    >\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"message__content-sent\">\r\n");
      out.write("                                    Congrats XD <br />\r\n");
      out.write("                                    Congrats XD <br />\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li class=\"chat-container__chat-room__received\">\r\n");
      out.write("                            <div class=\"message__img\">\r\n");
      out.write("                                <i class=\"fas fa-carrot\"></i>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"message__container\">\r\n");
      out.write("                                <div class=\"message__author\">\r\n");
      out.write("                                    <a href=\"../member/userDetail.html\"\r\n");
      out.write("                                        >상대방아이디</a\r\n");
      out.write("                                    ><span class=\"message__container--date\"\r\n");
      out.write("                                        >2020.10.06 16:04</span\r\n");
      out.write("                                    >\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"message__content-received\">\r\n");
      out.write("                                    Congrats XD <br />\r\n");
      out.write("                                    Congrats XD <br />\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li class=\"chat-container__chat-room__sent\">\r\n");
      out.write("                            <div class=\"message__container-sent\">\r\n");
      out.write("                                <div class=\"message__author\">\r\n");
      out.write("                                    <span class=\"message__container--date\"\r\n");
      out.write("                                        >2020.10.06 16:08</span\r\n");
      out.write("                                    >\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"message__content-sent\">\r\n");
      out.write("                                    Congrats XD <br />\r\n");
      out.write("                                    Congrats XD <br />\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li class=\"chat-container__chat-room__sent\">\r\n");
      out.write("                            <div class=\"message__container-sent\">\r\n");
      out.write("                                <div class=\"message__author\">\r\n");
      out.write("                                    <span class=\"message__container--date\"\r\n");
      out.write("                                        >2020.10.06 16:08</span\r\n");
      out.write("                                    >\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"message__content-sent\">\r\n");
      out.write("                                    Congrats XD <br />\r\n");
      out.write("                                    Congrats XD <br />\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li class=\"chat-container__chat-room__sent\">\r\n");
      out.write("                            <div class=\"message__container-sent\">\r\n");
      out.write("                                <div class=\"message__author\">\r\n");
      out.write("                                    <span class=\"message__container--date\"\r\n");
      out.write("                                        >2020.10.06 16:08</span\r\n");
      out.write("                                    >\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"message__content-sent\">\r\n");
      out.write("                                    Congrats XD <br />\r\n");
      out.write("                                    Congrats XD <br />\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li class=\"chat-container__chat-room__sent\">\r\n");
      out.write("                            <div class=\"message__container-sent\">\r\n");
      out.write("                                <div class=\"message__author\">\r\n");
      out.write("                                    <span class=\"message__container--date\"\r\n");
      out.write("                                        >2020.10.06 16:08</span\r\n");
      out.write("                                    >\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"message__content-sent\">\r\n");
      out.write("                                    Congrats XD <br />\r\n");
      out.write("                                    Congrats XD <br />\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li class=\"chat-container__chat-room__sent\">\r\n");
      out.write("                            <div class=\"message__container-sent\">\r\n");
      out.write("                                <div class=\"message__author\">\r\n");
      out.write("                                    <span class=\"message__container--date\"\r\n");
      out.write("                                        >2020.10.06 16:08</span\r\n");
      out.write("                                    >\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"message__content-sent\">\r\n");
      out.write("                                    Congrats XD <br />\r\n");
      out.write("                                    Congrats XD <br />\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                    <div class=\"chat-container__chat-room__footer\">\r\n");
      out.write("                        <input\r\n");
      out.write("                            class=\"chat-container__chat-room__footer--input\"\r\n");
      out.write("                            type=\"text\"\r\n");
      out.write("                            placeholder=\"Send message\"\r\n");
      out.write("                        />\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- 홈 버튼 -->\r\n");
      out.write("        <div class=\"scroll-btn\"></div>\r\n");
      out.write("        <!-- 하단 카피라이트 -->\r\n");
      out.write("        ");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("        <meta charset=\"UTF-8\" />\r\n");
      out.write("        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />\r\n");
      out.write("        <title>회원가입 :: 당근나라</title>\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"css/common.css\" />\r\n");
      out.write("        <script\r\n");
      out.write("            src=\"https://kit.fontawesome.com/797af710b1.js\"\r\n");
      out.write("            crossorigin=\"anonymous\"\r\n");
      out.write("            defer\r\n");
      out.write("        ></script>\r\n");
      out.write("        <script\r\n");
      out.write("            src=\"https://t1.daumcdn.net/mapjsapi/bundle/postcode/prod/postcode.v2.js\"\r\n");
      out.write("            defer\r\n");
      out.write("        ></script>\r\n");
      out.write("        <link\r\n");
      out.write("            rel=\"shortcut icon\"\r\n");
      out.write("            type=\"image/x-icon\"\r\n");
      out.write("            href=\"https://d1unjqcospf8gs.cloudfront.net/favicon.ico\"\r\n");
      out.write("        />\r\n");
      out.write("        <link\r\n");
      out.write("            href=\"https://fonts.googleapis.com/css2?family=Noto+Sans+KR:wght@400;500;700;900&display=swap\"\r\n");
      out.write("            rel=\"stylesheet\"\r\n");
      out.write("        />\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("        <footer class=\"footer\">\r\n");
      out.write("            <div class=\"footer-container\">\r\n");
      out.write("                <div class=\"footer-top\">\r\n");
      out.write("                    <div class=\"footer-top-logo\"></div>\r\n");
      out.write("                    <ul class=\"footer-top-list\">\r\n");
      out.write("                        <li class=\"footer-top-list-content\">\r\n");
      out.write("                            <a href=\"https://www.daangn.com/trust\"\r\n");
      out.write("                                >믿을 수 있는 중고거래</a\r\n");
      out.write("                            >\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li class=\"footer-top-list-content\">\r\n");
      out.write("                            <a href=\"https://www.daangn.com/wv/faqs\">\r\n");
      out.write("                                자주 묻는 질문</a\r\n");
      out.write("                            >\r\n");
      out.write("                        </li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                    <ul class=\"footer-top-list\">\r\n");
      out.write("                        <li class=\"footer-top-list-content\">\r\n");
      out.write("                            <a\r\n");
      out.write("                                href=\"https://www.notion.so/3d0197c137ec43d18ff739b5b254a3c8/\"\r\n");
      out.write("                            >\r\n");
      out.write("                                회사 소개\r\n");
      out.write("                            </a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li class=\"footer-top-list-content\">\r\n");
      out.write("                            <a href=\"https://ad.daangn.com/\"> 광고주센터 </a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li class=\"footer-top-list-content\">\r\n");
      out.write("                            <a href=\"https://town.daangn.com/\"> 동네가게 </a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                    <ul class=\"footer-top-list\">\r\n");
      out.write("                        <li class=\"footer-top-list-content\">\r\n");
      out.write("                            <a href=\"https://www.daangn.com/policy/terms\">\r\n");
      out.write("                                이용약관\r\n");
      out.write("                            </a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li class=\"footer-top-list-content\">\r\n");
      out.write("                            <a href=\"https://www.daangn.com/policy/privacy\">\r\n");
      out.write("                                개인정보 취급방침\r\n");
      out.write("                            </a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li class=\"footer-top-list-content\">\r\n");
      out.write("                            <a href=\"https://www.daangn.com/policy/location\">\r\n");
      out.write("                                위치기반서비스 이용약관\r\n");
      out.write("                            </a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"footer-bottom\">\r\n");
      out.write("                    <div class=\"footer-bottom-copyright\">\r\n");
      out.write("                        <ul class=\"footer-bottom-list-container\">\r\n");
      out.write("                            <li class=\"footer-bottom-list-conent\">\r\n");
      out.write("                                <address>고객문의 cs@daangnservice.com</address>\r\n");
      out.write("                                <address>제휴문의 contact@daangn.com</address>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li class=\"footer-bottom-list-conent\">\r\n");
      out.write("                                <address>\r\n");
      out.write("                                    사업자 등록번호 : 375-87-000-88\r\n");
      out.write("                                </address>\r\n");
      out.write("                                <address>\r\n");
      out.write("                                    서울특별시 구로구 디지털로 30길 28 609호\r\n");
      out.write("                                </address>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li class=\"footer-bottom-list-conent\">\r\n");
      out.write("                                ©Danggeun Market Inc.\r\n");
      out.write("                            </li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"footer-bottom-sns\">\r\n");
      out.write("                        <ul class=\"footer-bottom-sns-container\">\r\n");
      out.write("                            <li class=\"sns-icon\">\r\n");
      out.write("                                <a href=\"https://www.facebook.com/daangn\">\r\n");
      out.write("                                    <img\r\n");
      out.write("                                        src=\"https://d1unjqcospf8gs.cloudfront.net/assets/home/base/footer/icon-facebook-0563f4a93852d073b41f13b8bcabb03d47af3bb3a6755cdfedd8a73686c7f18c.svg\"\r\n");
      out.write("                                    />\r\n");
      out.write("                                </a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li class=\"sns-icon\">\r\n");
      out.write("                                <a\r\n");
      out.write("                                    href=\"https://www.instagram.com/daangnmarket/\"\r\n");
      out.write("                                >\r\n");
      out.write("                                    <img\r\n");
      out.write("                                        src=\"https://d1unjqcospf8gs.cloudfront.net/assets/home/base/footer/icon-instagram-2f6c88a461597907c114b7ce28eab053fcae791ed26417915fefb6f7c9f95756.svg\"\r\n");
      out.write("                                    />\r\n");
      out.write("                                </a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li class=\"sns-icon\">\r\n");
      out.write("                                <a href=\"https://blog.naver.com/daangn\">\r\n");
      out.write("                                    <img\r\n");
      out.write("                                        src=\"https://d1unjqcospf8gs.cloudfront.net/assets/home/base/footer/icon-blog-e1b0d512d1766a6962ec5bbb5b0803d2a6a9c55ad97db5ba9eebb76013caceba.svg\"\r\n");
      out.write("                                    />\r\n");
      out.write("                                </a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </footer>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("    </body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fchoose_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:choose
    org.apache.taglibs.standard.tag.common.core.ChooseTag _jspx_th_c_005fchoose_005f0 = (org.apache.taglibs.standard.tag.common.core.ChooseTag) _005fjspx_005ftagPool_005fc_005fchoose.get(org.apache.taglibs.standard.tag.common.core.ChooseTag.class);
    boolean _jspx_th_c_005fchoose_005f0_reused = false;
    try {
      _jspx_th_c_005fchoose_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fchoose_005f0.setParent(null);
      int _jspx_eval_c_005fchoose_005f0 = _jspx_th_c_005fchoose_005f0.doStartTag();
      if (_jspx_eval_c_005fchoose_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                    \t");
          if (_jspx_meth_c_005fwhen_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("                    \t");
          if (_jspx_meth_c_005fwhen_005f1(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("                    \t");
          if (_jspx_meth_c_005fwhen_005f2(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("                    ");
          int evalDoAfterBody = _jspx_th_c_005fchoose_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fchoose_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f0);
      _jspx_th_c_005fchoose_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fchoose_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fchoose_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f0 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    boolean _jspx_th_c_005fwhen_005f0_reused = false;
    try {
      _jspx_th_c_005fwhen_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fwhen_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      // /WEB-INF/views/header.jsp(63,21) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fwhen_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.mId != null}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fwhen_005f0 = _jspx_th_c_005fwhen_005f0.doStartTag();
      if (_jspx_eval_c_005fwhen_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t                    \t<ul class=\"header__fixed-bar-nav-list nav-list\">\r\n");
          out.write("\t                            <li class=\"nav-list-content drop\">\r\n");
          out.write("\t                                <span class=\"nav-list-text\">\r\n");
          out.write("\t                                    <span class=\"name\">");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.mId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</span>님 </span\r\n");
          out.write("\t                                ><img\r\n");
          out.write("\t                                    src=\"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAABmJLR0QA/wD/AP+gvaeTAAAA1ElEQVRIie2TsQ3CMBBF/zkLpMQLQO9zmV2IBBINJZQZgDAAVRAj0FBlhrRZwV1GwDQGhUhJnFQg+Xdn371nyzIQEvJfYeZMa50DEDPGBTOfmTn7Wuw0xdbaIzMXEyXCzRwAxO2NqF0YY0op5YKItlLKVZIk97qurQf8CiAFcKuqag/gMxN1u40xDydJm6ZZjkje8LWDbwA8e28wUTIK7xV4SLzgg4IBCfnCAYCGBK3TFnCP6NZSH7ivAABIKXUhop2rveBTI7TWuVLqhHkfMSTkV/MCeGNw/fvNnQwAAAAASUVORK5CYII=\"\r\n");
          out.write("\t                                />\r\n");
          out.write("\t                                <ul class=\"drop__container\">\r\n");
          out.write("\t                                    <a href=\"TBmyPage.do?mId=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.mId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\"><li>마이페이지</li></a>\r\n");
          out.write("\t                                    <a href=\"#\"><li>관심내역</li></a>\r\n");
          out.write("\t                                    <a href=\"#\"><li>판매내역</li></a>\r\n");
          out.write("\t                                    <a href=\"#\"><li>구매내역</li></a>\r\n");
          out.write("\t                                    <a href=\"TBLogout.do\"><li>로그아웃</li></a>\r\n");
          out.write("\r\n");
          out.write("\t                                    \r\n");
          out.write("\t                                </ul>\r\n");
          out.write("\t                            </li>\r\n");
          out.write("\t                            <li class=\"nav-list-content\">\r\n");
          out.write("\t                                <a href=\"#\">지도로 보기</a>\r\n");
          out.write("\t                            </li>\r\n");
          out.write("\t                        </ul>\r\n");
          out.write("                    \t");
          int evalDoAfterBody = _jspx_th_c_005fwhen_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fwhen_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f0);
      _jspx_th_c_005fwhen_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fwhen_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fwhen_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f1 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    boolean _jspx_th_c_005fwhen_005f1_reused = false;
    try {
      _jspx_th_c_005fwhen_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fwhen_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      // /WEB-INF/views/header.jsp(86,21) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fwhen_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.mId == null}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fwhen_005f1 = _jspx_th_c_005fwhen_005f1.doStartTag();
      if (_jspx_eval_c_005fwhen_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t                        <ul class=\"header__fixed-bar-nav-list nav-list\">\r\n");
          out.write("\t                            <li class=\"nav-list-content\">\r\n");
          out.write("\t                                <a href=\"TBjoinForm.do\">회원가입</a>\r\n");
          out.write("\t                            </li>\r\n");
          out.write("\t                            <li class=\"nav-list-content\">\r\n");
          out.write("\t                                <a href=\"TBlogin.do\">로그인</a>\r\n");
          out.write("\t                            </li>\r\n");
          out.write("\t                            <li class=\"nav-list-content\">\r\n");
          out.write("\t                                <a href=\"#\">지도로 보기</a>\r\n");
          out.write("\t                            </li>\r\n");
          out.write("\t                        </ul>                    \t\t\r\n");
          out.write("                    \t");
          int evalDoAfterBody = _jspx_th_c_005fwhen_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fwhen_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f1);
      _jspx_th_c_005fwhen_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fwhen_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fwhen_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f2 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    boolean _jspx_th_c_005fwhen_005f2_reused = false;
    try {
      _jspx_th_c_005fwhen_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fwhen_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      // /WEB-INF/views/header.jsp(99,21) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fwhen_005f2.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${tbm.mLevel == 3}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fwhen_005f2 = _jspx_th_c_005fwhen_005f2.doStartTag();
      if (_jspx_eval_c_005fwhen_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                              <ul class=\"header__fixed-bar-nav-list nav-list\">\r\n");
          out.write("                                 <li class=\"nav-list-content drop\">\r\n");
          out.write("                                <span class=\"nav-list-text\">\r\n");
          out.write("                                    Welcome ~!\r\n");
          out.write("                                    <span class=\"name\">관리자</span>님 </span\r\n");
          out.write("                                ><img\r\n");
          out.write("                                    src=\"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAABmJLR0QA/wD/AP+gvaeTAAAA1ElEQVRIie2TsQ3CMBBF/zkLpMQLQO9zmV2IBBINJZQZgDAAVRAj0FBlhrRZwV1GwDQGhUhJnFQg+Xdn371nyzIQEvJfYeZMa50DEDPGBTOfmTn7Wuw0xdbaIzMXEyXCzRwAxO2NqF0YY0op5YKItlLKVZIk97qurQf8CiAFcKuqag/gMxN1u40xDydJm6ZZjkje8LWDbwA8e28wUTIK7xV4SLzgg4IBCfnCAYCGBK3TFnCP6NZSH7ivAABIKXUhop2rveBTI7TWuVLqhHkfMSTkV/MCeGNw/fvNnQwAAAAASUVORK5CYII=\"\r\n");
          out.write("                                />\r\n");
          out.write("                                <ul class=\"drop__container\">\r\n");
          out.write("                                    <li><a href=\"../admin/adminManageList.html\">회원관리</a></li>\r\n");
          out.write("                                    <li><a href=\"#\">로그아웃</a></li>\r\n");
          out.write("                                </ul>\r\n");
          out.write("                            </li>\r\n");
          out.write("                            <li class=\"nav-list-content\">\r\n");
          out.write("                                <a href=\"#\">지도로 보기</a>\r\n");
          out.write("                            </li> \r\n");
          out.write("                        </ul>\r\n");
          out.write("                    \t");
          int evalDoAfterBody = _jspx_th_c_005fwhen_005f2.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fwhen_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f2);
      _jspx_th_c_005fwhen_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fwhen_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fwhen_005f2_reused);
    }
    return false;
  }
}
